import math
import os
import pandas as pd


def load_person1_data():
    """
    Load tracking and speed data generated by Person 1.
    """

    tracking = pd.read_csv("input/vehicle_tracking_clean.csv")
    speed = pd.read_csv("input/vehicle_speed_data.csv")

    return tracking, speed


def merge_data():
    """
    Merge tracking data with speed data.
    """

    tracking, speed = load_person1_data()

    merged = pd.merge(
        tracking,
        speed,
        on=["vehicle_id", "class"],
        how="left"
    )

    return merged


def detect_near_miss(merged_df, threshold=50):
    """
    Detect vehicles that are too close in the same frame.
    """

    events = []

    # Process each frame separately
    for frame in merged_df["frame"].unique():

        frame_data = merged_df[merged_df["frame"] == frame]

        vehicles = frame_data.to_dict("records")

        # Compare every vehicle with every other vehicle
        for i in range(len(vehicles)):
            for j in range(i + 1, len(vehicles)):

                v1 = vehicles[i]
                v2 = vehicles[j]

                distance = math.sqrt(
                    (v1["x_center"] - v2["x_center"]) ** 2 +
                    (v1["y_center"] - v2["y_center"]) ** 2
                )

                if distance < threshold:

                    events.append({
                        "frame": frame,
                        "vehicle_1": int(v1["vehicle_id"]),
                        "vehicle_2": int(v2["vehicle_id"]),
                        "distance": round(distance, 2),
                        "speed_vehicle_1": round(v1["speed_pixels_per_sec"], 2),
                        "speed_vehicle_2": round(v2["speed_pixels_per_sec"], 2)
                    })

    return events


if __name__ == "__main__":

    # Step 1: Merge Person 1 outputs
    merged = merge_data()

    # Step 2: Detect near misses
    events = detect_near_miss(merged)

    # Step 3: Create output folder
    os.makedirs("output", exist_ok=True)

    # Step 4: Save results
    events_df = pd.DataFrame(events)

    events_df.to_csv(
        "output/near_miss_events.csv",
        index=False
    )

    events_df.to_json(
        "output/near_miss_events.json",
        orient="records",
        indent=4
    )

    # Step 5: Display summary
    print("\n========== PERSON 2 OUTPUT ==========")
    print(f"Total Near Miss Events: {len(events)}")
    print("CSV File : output/near_miss_events.csv")
    print("JSON File: output/near_miss_events.json")
    print("=====================================")

    # Show first few events
    if len(events) > 0:
        print("\nFirst 10 Near Miss Events:\n")
        print(events_df.head(10))
    else:
        print("\nNo near miss events detected.")